// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClientPortal.Api.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int ClientId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public string ShippingFirstName { get; set; }

    public string ShippingLastName { get; set; }

    public string ShippingStreetAddress { get; set; }

    public string ShippingCity { get; set; }

    public string ShippingProvince { get; set; }

    public string ShippingPostalCode { get; set; }

    public string ShippingCountry { get; set; }

    public virtual Client Client { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}